### ISSUE TITLE
[Feature Request]: Skip sensor updates between shutdown and startup time

### ISSUE THREAD

**Issue by dannerph** [wlcrs/huawei_solar#234]
### Describe your feature request

Thanks for this great and continuously improving integration!
My Huawei SUN2000-20KTL-M0 is only used for feed-in and goes to standby overnight. During standby, ModBus is not active and the integration shows “unavailable” for all sensors. Would it be possible to keep the last values, i.e., not sending ModBus requests between the shutdown time and startup time, which seem to be available from the device?

I first want to get your opinion on this problem before working on a PR.

### Proper usage

- [X] I confirm that this is not a bug report

**Comment by wlcrs** [comment]
I have already thought about this, but decided against it for the following reasons:

1. Those startup and shutdown times are read the same way as all other sensors. So I cannot use them to determine if I should update the values.

2. It would be very difficult for me to properly implement something like this: what must I do when Home Assistant starts when the inverter is in standby for instance? Every sensor would need it's own approach: some keep their latest values before going in standby, some should be 0 when the inverter is in standby, etc.

3. The sensors being unavailable is the true status of each value: the integration cannot determine the latest value for them at that moment. How should I differentiate between a network failure that is preventing the Modbus connection and the inverter not answering because it went to sleep?

This is why I will not implement this feature. Of course, as this is an open source project, someone else is welcome to contribute this. Just reply in this issue and I'll reopen it for you.

In the meantime, I would suggest that you use HA templates and helper entities to work around this if this really bothers you.
