### ISSUE TITLE
could not read register value, is an other device already connected?

### ISSUE THREAD

**Issue by Breina** [wlcrs/huawei_solar#3]
When adding the integration through the GUI, after a while, the following error is shown:

```
Logger: custom_components.huawei_solar.config_flow
Source: custom_components/huawei_solar/config_flow.py:54
Integration: Huawei Solar
First occurred: 15:36:56 (1 occurrences)
Last logged: 15:36:56

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/huawei_solar/config_flow.py", line 80, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/huawei_solar/config_flow.py", line 54, in validate_input
    model_name = inverter.get(ATTR_MODEL_ID).value
  File "/usr/local/lib/python3.9/site-packages/huawei_solar/huawei_solar.py", line 265, in get
    response = self.read_register(reg.register, reg.length)
  File "/usr/local/lib/python3.9/site-packages/huawei_solar/huawei_solar.py", line 312, in read_register
    raise ReadException(message)
huawei_solar.huawei_solar.ReadException: could not read register value, is an other device already connected?
```

I have previously used Emilv2's integration but I would love to switch to this one. I've removed his from HACS and added yours. But at least the setup worked over there.

I can also run this testing code successfully, just to show that a successful read can be performed.

```
client = ModbusClient("192.168.1.40", port=502)

client.connect()

if client.connect():
    time.sleep(1)

    rr = client.read_holding_registers(0x7D50, 0x02, unit=1)  # 32080 => active_power

    activePowerInv = rr.registers[1]

    print(activePowerInv)
```

**Comment by JacoboSanchez** [comment]
Your error seems to be in the line getting the model_id. 
In the [underlying python library used ](https://gitlab.com/Emilv2/huawei-solar/-/blob/master/src/huawei_solar/huawei_solar.py#L408) model_id relates to register 30070 of length 1 (type u16) . Can you repeat your test code using such register?  something like:
`client.read_holding_registers(30070, 0x01, unit=1)`

**Comment by Breina** [comment]
That does seem to work as well; it outputs `429`.

For reference:

    rr = client.read_holding_registers(30070, 0x01, unit=1)
    activePowerInv = rr.registers[0]

**Comment by JacoboSanchez** [comment]
Well I don't really know then.. just a final guess. In your code you use "unit=1" did you specify also 1 in the integration configuration? not 100% sure that's the same parameter but just in case...

**Comment by Breina** [comment]
Yeah I've tried, doesn't seem to matter what I put into it. I'll fiddle around with it in the coming days, I'll post the solution if I find one. Thanks for your insight so far though!

**Comment by Breina** [comment]
Created a PR fixing this issue. :)

**Comment by wlcrs** [comment]
Hi @Breina , thank you for finding the issue and fixing it. However, for the moment I don't see any PR for this repo. Can you please retry creating a PR, I'll gladly approve it!

**Comment by Breina** [comment]
Ah that should do it! :)

**Comment by Marchellos** [comment]
Hello friends,

HUAWEI 17KTL M0 (SPC139)
Dongle WIFI/FE (SPC123)

I finally have port 502 available in my network.
Now I run into the following problem:

Logger: huawei_solar.huawei_solar
Source: /usr/local/lib/python3.9/site-packages/huawei_solar/huawei_solar.py:437
First occurred: 1:30:47 PM (1 occurrences)
Last logged: 1:30:47 PM

The dongle seems to be connected via both WIFI and LAN (open on both port 502 ).
IP 192.168.0.8 and 192.168.0.9

----------------------------------------------------------------------------
could not read register value, is an other device already connected?


This error originated from a custom integration.

Logger: custom_components.huawei_solar.config_flow
Source: custom_components/huawei_solar/config_flow.py:47
Integration: Huawei Solar
First occurred: 1:30:47 PM (1 occurrences)
Last logged: 1:30:47 PM
----------------------------------------------------------------------------------
Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/huawei_solar/huawei_solar.py", line 419, in read_register
    response = await client.protocol.read_holding_registers(
  File "/usr/local/lib/python3.9/site-packages/pymodbus/client/asynchronous/async_io/__init__.py", line 35, in execute
    resp = await asyncio.wait_for(req, timeout=self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Connection lost during request

During handling of the above exception, another exception occurred:
--------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/config/custom_components/huawei_solar/config_flow.py", line 77, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/huawei_solar/config_flow.py", line 47, in validate_input
    model_name = (await inverter.get(ATTR_MODEL_NAME)).value
  File "/usr/local/lib/python3.9/site-packages/huawei_solar/huawei_solar.py", line 394, in get
    response = await self.read_register(await self.client, reg.register, reg.length)
  File "/usr/local/lib/python3.9/site-packages/huawei_solar/huawei_solar.py", line 438, in read_register
    raise ReadException(message)
huawei_solar.huawei_solar.ReadException: could not read register value, is an other device already connected?

--------------------------------------------------------------------------------------------
Logger: pymodbus.client.asynchronous.async_io
Source: /usr/local/lib/python3.9/site-packages/pymodbus/client/asynchronous/async_io/__init__.py:307
First occurred: 1:30:38 PM (9 occurrences)
Last logged: 1:31:00 PM

Failed to connect: Multiple exceptions: [Errno 111] Connect call failed ('::1', 502, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 502)
------------------------------------------------------------------------

**Comment by wlcrs** [comment]
Your inverter closes the connection instead of answering any queries it seems.

Can you check if ModbusTCP is enabled without any restrictions? (cfr. step 6 and later of https://forum.huawei.com/enterprise/en/modbus-tcp-guide/thread/789585-100027 )

Is your inverter/dongle updated to the latest firmware?

You can also try using another Modbus-client to test if you can read register 30000 .

**Comment by Marchellos** [comment]
Hello Thijs,

Thanks for your response.

If I use SPC126 then port 502 is closed according to the port scanner.
You can only set this via steps 6-7 if you have an Android phone.
I have an iPhone...
That's why I used SPC123, port 502 is open by default (checked with port
scanner.).
So I hope this is sufficient.
I read that more users had a problem with this, and that's why they stayed
with SPC 123.

HUAWEI 17KTL M0 (SPC140)
Dongle WIFI/FE (SPC123).

*"You can also try using another Modbus-client to test if you can read
register 30000 "*

Where can I find the instructions on how to do this?

[image: 4041227e-e8bd-4a65-8a5e-347736e28d30.jpg]


What is this MODE setting ?
It defaults to NA.
Here I set it to R485 as an example, but this setting keeps going back to
NA.


Op vr 7 jan. 2022 om 14:45 schreef Thijs Walcarius ***@***.***

**Comment by wlcrs** [comment]
The inverter closes the connection instead of answering the query after issueing a read_register (0x03) command, so having an open 502 port is clearly not enough.

The image you tried to include is not visible, so I cannot see what you are asking.

I've only worked with Modbus directly via Python. A minimal example to debug:

```
from pymodbus.client.sync import ModbusTcpClient as ModbusClient
client = ModbusClient('<ip>', port=502)
client.connect()
client.read_holding_register(address=30000, count=15 ,unit=0)
```

If you want to use a GUI to query, you'll have to search for yourself (maybe http://www.minaandrawos.com/tcp-modbus-examiner-tool/ works for you?)
