### ISSUE TITLE
[Feature Request]: Optimizer device name

### ISSUE THREAD

**Issue by gilder0** [wlcrs/huawei_solar#76]
### Describe your feature request

I tried to setup optimizer device name to be similar to what we see in FusionSolar app.

and i change 
[__init__.py:118](https://github.com/wlcrs/huawei_solar/blob/7ad1dd7de1fd776ca5ae85e358511c9943706788/__init__.py#L118)
to :                            
name=f"{optimizer.string_number}.{optimizer.position_in_current_string} {optimizer.sn}",

but i get strange effect .
In my instalation i've got 2 PV string and string numer where returned 257 or 514 .   position_in_current_string was empty

in specification it is written that it is 2 byte number, but i suspect it is 1 byte integer sent twice .

Can anyone confirm that ? maybe there is someone who has more then 2 pv strings.

**Comment by wlcrs** [comment]
I've adapted the parsing so that the first byte of string_number is ignored: https://gitlab.com/Emilv2/huawei-solar/-/commit/b8edafa24d32fbcc0c3b0742ac05d7a2e81bdf0b . 

Note that position_in_string is empty because I explicitly test it on being different from 0xFFFF. All optimizers in my installation report this value.

![image](https://user-images.githubusercontent.com/2150060/177190159-cdc18c00-1601-43d6-8dc6-ae767e877929.png)
